version: '3'

services:
  frontend:
    image: trixxtazz/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
  api:
    image: trixxtazz/time-app-api-dev
    ports:
      - '5555:5000'
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: 'password'
      MYSQL_DB: 'time_db'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: time_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data_pub:/var/lib/mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data_pub: